/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./**/*.{html,js}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#3a485b",
        "surface": "#faf8ff",
        "on-primary-container": "#efefff",
        "surface-container-highest": "#dae2fd",
        "secondary": "#515f74",
        "secondary-fixed-dim": "#b9c7df",
        "on-surface-variant": "#434655",
        "inverse-primary": "#b7c4ff",
        "tertiary-container": "#bc4800",
        "surface-bright": "#faf8ff",
        "surface-dim": "#d2d9f4",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffede6",
        "on-primary": "#ffffff",
        "on-background": "#131b2e",
        "tertiary": "#943700",
        "surface-container-high": "#e2e7ff",
        "inverse-surface": "#283044",
        "primary": "#0d46d1",
        "on-secondary": "#ffffff",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "secondary-container": "#d5e3fc",
        "tertiary-fixed-dim": "#ffb596",
        "surface-tint": "#2151da",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#eef0ff",
        "secondary-fixed": "#d5e3fc",
        "on-primary-fixed": "#001551",
        "tertiary-fixed": "#ffdbcd",
        "background": "#faf8ff",
        "on-surface": "#131b2e",
        "primary-container": "#3761ea",
        "surface-container-low": "#f2f3ff",
        "primary-fixed": "#b7c4ff",
        "on-primary-fixed-variant": "#001551",
        "secondary-fixed-variant": "#3a485b",
        "on-secondary-container": "#0b1a2e",
        "error": "#ba1a1a",
        "on-error-container": "#410e0b",
        "primary-fixed-dim": "#8fa6ff",
        "outline": "#727785",
        "outline-variant": "#c1c5d1",
        "surface-container": "#edf0ff",
        "surface-variant": "#dee1ed",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        "surface-dim": "#d2d9f4",
        "surface-bright": "#faf8ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f3ff",
        "surface-container": "#edf0ff",
        "surface-container-high": "#e2e7ff",
        "surface-container-highest": "#dae2fd",
        "on-surface": "#131b2e",
        "on-surface-variant": "#434655",
        "outline": "#727785",
        "outline-variant": "#c1c5d1",
        "inverse-surface": "#283044",
        "inverse-on-surface": "#eef0ff",
        "inverse-primary": "#b7c4ff",
        "background": "#faf8ff",
        "on-background": "#131b2e",
        "primary": "#0d46d1",
        "primary-container": "#3761ea",
        "on-primary": "#ffffff",
        "on-primary-container": "#efefff",
        "primary-fixed": "#b7c4ff",
        "primary-fixed-dim": "#8fa6ff",
        "on-primary-fixed": "#001551",
        "on-primary-fixed-variant": "#001551",
        "secondary": "#515f74",
        "secondary-container": "#d5e3fc",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#0b1a2e",
        "secondary-fixed": "#d5e3fc",
        "secondary-fixed-dim": "#b9c7df",
        "on-secondary-fixed": "#001551",
        "on-secondary-fixed-variant": "#3a485b",
        "tertiary": "#943700",
        "tertiary-container": "#bc4800",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#ffede6",
        "tertiary-fixed": "#ffdbcd",
        "tertiary-fixed-dim": "#ffb596",
        "on-tertiary-fixed": "#2e1500",
        "on-tertiary-fixed-variant": "#5d1f00",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#410e0b",
        "surface": "#faf8ff",
        "surface-variant": "#dee1ed",
        "surface-tint": "#2151da",
        "shadow": "#000000",
        "scrim": "#000000",
        "surface-container-lowest": "#ffffff"
      },
      fontFamily: {
        'sans': ['Inter', 'sans-serif'],
        'display': ['Manrope', 'sans-serif']
      }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}